version: '3.8'

services:
  guardit:
    build: .
    container_name: guardit
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Mount scripts folder if you want to test scripts inside the container
      - ./scripts:/app/scripts

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=simpod-json-datasource
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
